### ISSUE TITLE
[BUG REPORT] 在社区复制markdown链接时出现404

### ISSUE THREAD

**Issue by BrahmaMantra** [DragonOS-Community/Community#10]
复现步骤：右键标题--复制链接--打开链接
![image](https://github.com/DragonOS-Community/Community/assets/140599389/6a2ddea9-928d-43e7-89a9-25b8ae1bb691)
![image](https://github.com/DragonOS-Community/Community/assets/140599389/a1afebc4-d779-4fc0-88be-53a4d4fcebfd)

**Comment by fslongjin** [comment]
这个是vue press2的问题，还在等他们的更新，我上周已经关注到他们的PR了

**Comment by fslongjin** [comment]
更新了vuepress2的版本，已经解决了
